baseURL = "https://example.com"
languageCode = "en-us"
themesDir    = "themes"
theme                      = "AllinOne"
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

title                      = "KTZL"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/LogoV.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "KTZL"
  description              = ["Welcome to Karma Tekchen Zabsal Ling",
"Toronto Thrangu Centre",  "Through this site, we hope to connect with all students of Lama Tashi worldwide and to anyone who is interested to learn more about Tibetan Buddhism."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "ktzl88@gmail.com"
 # github                   = "//github.com/you"
 # linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/ktzl.org"
 # googleplus               = "//google.com/ktzl88@gmail.com"
# twitter                  = "//twitter.com/you" 
 # px500                    = "//px500"
 # instagram                = "//instagram.com/you"
 # include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    